
service: severlessdevopslab


provider:
  name: aws
  region: us-east-1
  runtime: python3.8



functions:
  hello:
    handler: handler.hello
    events:
    - http:
         path: users/create
         method: get
